#
# [ Database Configuration Section ]
#

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blood
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 9095

#
# [ Other Configuration Attributes ]
#
