#
# [ Database Configuration Section ]
#

spring:
  datasource:
    url: jdbc:h2:mem:USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
server:
  port: 9095


#
# [ Other Configuration Attributes ]
#
